### ISSUE TITLE
Tagoio cli v1.6.1 is not versioned correctly

### ISSUE THREAD

**Issue by CarterCall1** [tago-io/tagoio-cli#17]
Recently downloaded the tago cli and got the following error message when running it.

On Windows machine.

`Error: ENOENT: no such file or directory, open 'C:\Users\User\source\repos\tago\node_modules\@tago-io\cli\build\lib\package.json'`

After more digging found that there was a v1.6.1 that should have fixed that issue. 

But when I checked my cli version it was v1.6.0. Running npm update did not update the package.

However, after downloading the source code of v1.6.1 the package version is still v1.6.0 in the package.json file. I'm assuming there must be some sort of conflict here in the package manager since there are two releases with the same package version.

**Comment by mateuscardosodeveloper** [comment]
This issue was resolved in release [1.7.0](https://github.com/tago-io/tagoio-cli/releases/tag/v1.7.0) Please update or reinstall to the latest version, and it should work without any errors on Windows. Let me know if you encounter any further issues after updating!
